/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "VoltMon_ReadVoltageProject_mV.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_VoltMon_ReadVoltageProject_mV_LowBand_LowerBoundaryPlus1(void);
extern void test_VoltMon_ReadVoltageProject_mV_LowBand_MidValue(void);
extern void test_VoltMon_ReadVoltageProject_mV_LowBand_UpperBoundaryMinus1(void);
extern void test_VoltMon_ReadVoltageProject_mV_MiddleBand_LowerBoundary(void);
extern void test_VoltMon_ReadVoltageProject_mV_MiddleBand_MidValue(void);
extern void test_VoltMon_ReadVoltageProject_mV_MiddleBand_UpperBoundary(void);
extern void test_VoltMon_ReadVoltageProject_mV_MiddleBand_SameValues(void);
extern void test_VoltMon_ReadVoltageProject_mV_HighBand_LowerBoundaryPlus1(void);
extern void test_VoltMon_ReadVoltageProject_mV_HighBand_MidValue(void);
extern void test_VoltMon_ReadVoltageProject_mV_HighBand_UpperBoundaryMinus1(void);
extern void test_VoltMon_ReadVoltageProject_mV_OutOfRange_AtLowerBoundary(void);
extern void test_VoltMon_ReadVoltageProject_mV_OutOfRange_AtUpperBoundary(void);
extern void test_VoltMon_ReadVoltageProject_mV_OutOfRange_AboveUpperBoundary(void);
extern void test_VoltMon_ReadVoltageProject_mV_OutOfRange_MaxUint16(void);
extern void test_VoltMon_ReadVoltageProject_mV_MiddleBand_FilteredZero(void);
extern void test_VoltMon_ReadVoltageProject_mV_MiddleBand_FilteredMaxValue(void);
extern void test_VoltMon_ReadVoltageProject_mV_BoundaryTransition_5000(void);
extern void test_VoltMon_ReadVoltageProject_mV_BoundaryTransition_10000(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_VoltMon_ReadVoltageProject_mV.c");
  run_test(test_VoltMon_ReadVoltageProject_mV_LowBand_LowerBoundaryPlus1, "test_VoltMon_ReadVoltageProject_mV_LowBand_LowerBoundaryPlus1", 39);
  run_test(test_VoltMon_ReadVoltageProject_mV_LowBand_MidValue, "test_VoltMon_ReadVoltageProject_mV_LowBand_MidValue", 54);
  run_test(test_VoltMon_ReadVoltageProject_mV_LowBand_UpperBoundaryMinus1, "test_VoltMon_ReadVoltageProject_mV_LowBand_UpperBoundaryMinus1", 69);
  run_test(test_VoltMon_ReadVoltageProject_mV_MiddleBand_LowerBoundary, "test_VoltMon_ReadVoltageProject_mV_MiddleBand_LowerBoundary", 90);
  run_test(test_VoltMon_ReadVoltageProject_mV_MiddleBand_MidValue, "test_VoltMon_ReadVoltageProject_mV_MiddleBand_MidValue", 106);
  run_test(test_VoltMon_ReadVoltageProject_mV_MiddleBand_UpperBoundary, "test_VoltMon_ReadVoltageProject_mV_MiddleBand_UpperBoundary", 122);
  run_test(test_VoltMon_ReadVoltageProject_mV_MiddleBand_SameValues, "test_VoltMon_ReadVoltageProject_mV_MiddleBand_SameValues", 138);
  run_test(test_VoltMon_ReadVoltageProject_mV_HighBand_LowerBoundaryPlus1, "test_VoltMon_ReadVoltageProject_mV_HighBand_LowerBoundaryPlus1", 160);
  run_test(test_VoltMon_ReadVoltageProject_mV_HighBand_MidValue, "test_VoltMon_ReadVoltageProject_mV_HighBand_MidValue", 176);
  run_test(test_VoltMon_ReadVoltageProject_mV_HighBand_UpperBoundaryMinus1, "test_VoltMon_ReadVoltageProject_mV_HighBand_UpperBoundaryMinus1", 192);
  run_test(test_VoltMon_ReadVoltageProject_mV_OutOfRange_AtLowerBoundary, "test_VoltMon_ReadVoltageProject_mV_OutOfRange_AtLowerBoundary", 214);
  run_test(test_VoltMon_ReadVoltageProject_mV_OutOfRange_AtUpperBoundary, "test_VoltMon_ReadVoltageProject_mV_OutOfRange_AtUpperBoundary", 229);
  run_test(test_VoltMon_ReadVoltageProject_mV_OutOfRange_AboveUpperBoundary, "test_VoltMon_ReadVoltageProject_mV_OutOfRange_AboveUpperBoundary", 244);
  run_test(test_VoltMon_ReadVoltageProject_mV_OutOfRange_MaxUint16, "test_VoltMon_ReadVoltageProject_mV_OutOfRange_MaxUint16", 259);
  run_test(test_VoltMon_ReadVoltageProject_mV_MiddleBand_FilteredZero, "test_VoltMon_ReadVoltageProject_mV_MiddleBand_FilteredZero", 278);
  run_test(test_VoltMon_ReadVoltageProject_mV_MiddleBand_FilteredMaxValue, "test_VoltMon_ReadVoltageProject_mV_MiddleBand_FilteredMaxValue", 294);
  run_test(test_VoltMon_ReadVoltageProject_mV_BoundaryTransition_5000, "test_VoltMon_ReadVoltageProject_mV_BoundaryTransition_5000", 309);
  run_test(test_VoltMon_ReadVoltageProject_mV_BoundaryTransition_10000, "test_VoltMon_ReadVoltageProject_mV_BoundaryTransition_10000", 325);

  return UNITY_END();
}
