/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "EDD_Crc8ComputeInternal.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_EDD_Crc8ComputeInternal_EmptyData(void);
extern void test_EDD_Crc8ComputeInternal_SingleByte(void);
extern void test_EDD_Crc8ComputeInternal_SingleByteNonZero(void);
extern void test_EDD_Crc8ComputeInternal_TwoBytes(void);
extern void test_EDD_Crc8ComputeInternal_AllZeros(void);
extern void test_EDD_Crc8ComputeInternal_AlternatingPattern(void);
extern void test_EDD_Crc8ComputeInternal_LongData(void);
extern void test_EDD_Crc8ComputeInternal_ReturnValueRange(void);
extern void test_EDD_Crc8ComputeInternal_Consistency(void);
extern void test_EDD_Crc8ComputeInternal_DifferentLengths(void);
extern void test_EDD_Crc8ComputeInternal_BoundaryValue(void);
extern void test_EDD_Crc8ComputeInternal_PotentialOverflowValues(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_EDD_Crc8ComputeInternal.c");
  run_test(test_EDD_Crc8ComputeInternal_EmptyData, "test_EDD_Crc8ComputeInternal_EmptyData", 26);
  run_test(test_EDD_Crc8ComputeInternal_SingleByte, "test_EDD_Crc8ComputeInternal_SingleByte", 40);
  run_test(test_EDD_Crc8ComputeInternal_SingleByteNonZero, "test_EDD_Crc8ComputeInternal_SingleByteNonZero", 55);
  run_test(test_EDD_Crc8ComputeInternal_TwoBytes, "test_EDD_Crc8ComputeInternal_TwoBytes", 70);
  run_test(test_EDD_Crc8ComputeInternal_AllZeros, "test_EDD_Crc8ComputeInternal_AllZeros", 90);
  run_test(test_EDD_Crc8ComputeInternal_AlternatingPattern, "test_EDD_Crc8ComputeInternal_AlternatingPattern", 106);
  run_test(test_EDD_Crc8ComputeInternal_LongData, "test_EDD_Crc8ComputeInternal_LongData", 120);
  run_test(test_EDD_Crc8ComputeInternal_ReturnValueRange, "test_EDD_Crc8ComputeInternal_ReturnValueRange", 139);
  run_test(test_EDD_Crc8ComputeInternal_Consistency, "test_EDD_Crc8ComputeInternal_Consistency", 154);
  run_test(test_EDD_Crc8ComputeInternal_DifferentLengths, "test_EDD_Crc8ComputeInternal_DifferentLengths", 168);
  run_test(test_EDD_Crc8ComputeInternal_BoundaryValue, "test_EDD_Crc8ComputeInternal_BoundaryValue", 185);
  run_test(test_EDD_Crc8ComputeInternal_PotentialOverflowValues, "test_EDD_Crc8ComputeInternal_PotentialOverflowValues", 199);

  return UNITY_END();
}
