/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "Subfunction_Request_Out_Of_Range.h"
#include "unity.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_Subfunction_Request_Out_Of_Range_WithNullErrCode(void);
extern void test_Subfunction_Request_Out_Of_Range_WithValidErrCode(void);
extern void test_Subfunction_Request_Out_Of_Range_WithNullOutput(void);
extern void test_Subfunction_Request_Out_Of_Range_WithNullSize(void);
extern void test_Subfunction_Request_Out_Of_Range_WithAllValidPointers(void);
extern void test_Subfunction_Request_Out_Of_Range_OutputAndSizeUnchanged(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_Subfunction_Request_Out_Of_Range.c");
  run_test(test_Subfunction_Request_Out_Of_Range_WithNullErrCode, "test_Subfunction_Request_Out_Of_Range_WithNullErrCode", 13);
  run_test(test_Subfunction_Request_Out_Of_Range_WithValidErrCode, "test_Subfunction_Request_Out_Of_Range_WithValidErrCode", 28);
  run_test(test_Subfunction_Request_Out_Of_Range_WithNullOutput, "test_Subfunction_Request_Out_Of_Range_WithNullOutput", 45);
  run_test(test_Subfunction_Request_Out_Of_Range_WithNullSize, "test_Subfunction_Request_Out_Of_Range_WithNullSize", 61);
  run_test(test_Subfunction_Request_Out_Of_Range_WithAllValidPointers, "test_Subfunction_Request_Out_Of_Range_WithAllValidPointers", 76);
  run_test(test_Subfunction_Request_Out_Of_Range_OutputAndSizeUnchanged, "test_Subfunction_Request_Out_Of_Range_OutputAndSizeUnchanged", 93);

  return UNITY_END();
}
