/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "checkMsgDataLength.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_checkMsgDataLength_ValidMinimumBoundary(void);
extern void test_checkMsgDataLength_ValidMaximumBoundary(void);
extern void test_checkMsgDataLength_ValidMiddleValue(void);
extern void test_checkMsgDataLength_InvalidZero(void);
extern void test_checkMsgDataLength_InvalidAboveMaximum(void);
extern void test_checkMsgDataLength_InvalidLargeValue(void);
extern void test_checkMsgDataLength_InvalidMaxUint16(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_checkMsgDataLength.c");
  run_test(test_checkMsgDataLength_ValidMinimumBoundary, "test_checkMsgDataLength_ValidMinimumBoundary", 14);
  run_test(test_checkMsgDataLength_ValidMaximumBoundary, "test_checkMsgDataLength_ValidMaximumBoundary", 24);
  run_test(test_checkMsgDataLength_ValidMiddleValue, "test_checkMsgDataLength_ValidMiddleValue", 34);
  run_test(test_checkMsgDataLength_InvalidZero, "test_checkMsgDataLength_InvalidZero", 44);
  run_test(test_checkMsgDataLength_InvalidAboveMaximum, "test_checkMsgDataLength_InvalidAboveMaximum", 54);
  run_test(test_checkMsgDataLength_InvalidLargeValue, "test_checkMsgDataLength_InvalidLargeValue", 64);
  run_test(test_checkMsgDataLength_InvalidMaxUint16, "test_checkMsgDataLength_InvalidMaxUint16", 74);

  return UNITY_END();
}
